### ISSUE TITLE
Better packaging

### ISSUE THREAD

**Issue by thatarchguy** [StackFocus/PostMaster#105]
As much as I'd love to push people to use docker more for this app, we should at least look into a better way of installing. Preferably a .deb/.rpm package. This shouldn't  be _too hard_ with tools like fpm or sites like https://packager.io/.

**Comment by thatarchguy** [comment]
So I really like chef-omnibus. It takes all the chef recipes you need to deploy and packages it all into a package for you to install using your package manager.

But...I don't like chef at all :astonished: 

So I found how to do this with ansible. And it's pretty baller. We can have travis or some free CI service build the package for us.

First, we have to convert postmaster to use ansible to deploy. Which I think is a step in the right direction to begin with. Then we build the package using FPM and specifying a playbook as the install script. 

`fpm -s dir -t deb -n "your_app" -v 1.0 --prefix /opt/your_app/git --after-install ops/ansible/run_ansible.sh ./`
the `run_ansible.sh` script is literally just a bash script that does `ansible -i "localhost," -c local /opt/your_app/git/ops/ansible/site.yml`

I'm still working out the details, but it's working for me so far.

**Comment by PrahlM93** [comment]
@thatarchguy nice work. Do you wanna try deploying SwagMail like this first as a demo since it's easier?

**Comment by thatarchguy** [comment]
pffttttt challenge accepted
