### ISSUE TITLE
Have log file be set via command line

### ISSUE THREAD

**Issue by PrahlM93** [StackFocus/PostMaster#107]
Currently, the log file location is set through the web interface, this should really be set via manage.py and set in config.py for protection.

**Comment by PrahlM93** [comment]
@thatarchguy, can you handle this?

**Comment by thatarchguy** [comment]
So remove the option to set the logfile location from the web interface and have it be set in the manage.py cli?

**Comment by PrahlM93** [comment]
Exactly. That way if the admin account is compromised, at least the log file location can't be changed by the attacker.
