### ISSUE TITLE
Proper Changelog

### ISSUE THREAD

**Issue by thatarchguy** [StackFocus/PostMaster#121]
I want to implement a proper changelog like hashicorp's projects do. It's helpful to go to a project and check the changelog to see what's new and how active development has been.

We can have a CHANGELOG.md or a spot in our docs (or both!)
I think new features coming in should end with a commit to the changelog file.

**Comment by PrahlM93** [comment]
@thatarchguy, I agree. I'll give this a start.

**Comment by PrahlM93** [comment]
#122 covers this
