### ISSUE TITLE
Have Ansible perform a database migration after package update

### ISSUE THREAD

**Issue by PrahlM93** [StackFocus/PostMaster#125]

**Comment by PrahlM93** [comment]
This should run our custom "createdb" command instead of the "migrate" command, otherwise, when we add additional configuration options, they wouldn't be added to the database.

**Comment by thatarchguy** [comment]
I'm still trying to figure out how the migrations will work. But yeah I agree, we should be using createdb or a similar function that calls the add_default_settings function.

**Comment by thatarchguy** [comment]
Related #129
