### ISSUE TITLE
Track db migrations in version control

### ISSUE THREAD

**Issue by thatarchguy** [StackFocus/PostMaster#129]
I didn't quite understand the flask-migrate process. 

It becomes really useful when doing upgrade of the software that requires a database migration. 

Instead of having the user generate their own migrations with `python manage.py db migrate && python manage.py db upgrade`, we can have finer control between versions and such if we track the migrations in git. 

They simply do a `python manage.py db upgrade` and it will apply each migration in order.

**Comment by PrahlM93** [comment]
As I understand it, this won't work because the user won't have the table in their database that keeps track of the state of migrations. Maybe there is a way around it though.

**Comment by thatarchguy** [comment]
hm.. that makes this very difficult to do properly. I know django handles this pretty seamlessly.

**Comment by thatarchguy** [comment]
If they have the `migrations/` folder and the database created (just `create database servermail`), then the user can simply run `python manage.py db upgrade` and it works fine.

If the user already has it built and needs to upgrade to latest version, they simply run `python manage.py db update`


The problem is that the ` python manage.py createdb` command uses the folder `db/migrations` instead of `migrations`. Is there a reason for it to go into the `db/migrations` folder? We can override the default with `--directory db/migrations` with the current layout. But that seems unnecessary unless I am mistaken?

**Comment by PrahlM93** [comment]
@thatarchguy, so the reason why we stored the migrations in the db folder was to allow us to mount the /opt/postmaster/git/db folder in Docker. We couldn't mount /opt/postmaster/git/migrations because the migration would fail because a folder already existed.
