### ISSUE TITLE
Add basic management of admins via the CLI

### ISSUE THREAD

**Issue by PrahlM93** [StackFocus/PostMaster#144]
manage.py (Flask-Script) should be expanded to give an admin the ability to unlock an admin account and to reset an admin account's password via the CLI.

**Comment by thatarchguy** [comment]
Doesn't flask .11 add click to the cli? I don't know if this replaces flask-script (our manage.py), but it may be easier to work with the cli options using click.

**Comment by PrahlM93** [comment]
@thatarchguy, the problem is that Flask-Migrate doesn't integrate with Click yet. We'd then remove some functionality from the CLI. Let's wait for Miguel to port Flask-Migrate to be able to use Click.

**Comment by PrahlM93** [comment]
#145 addresses this
