### ISSUE TITLE
Cleanup requirements.txt

### ISSUE THREAD

**Issue by PrahlM93** [StackFocus/PostMaster#154]
Currently, requirements.txt is just a dump of `pip freeze`. We should transition to only include PostMaster's direct dependencies excluding the dependencies of the dependencies. This will make keeping requirements.txt easier to keep up to date.

**Comment by thatarchguy** [comment]
Should we do https://github.com/nvie/pip-tools ?

**Comment by PrahlM93** [comment]
@thatarchguy, yeah I like that approach. Exactly what we need.
