### ISSUE TITLE
Release PostMaster v1.1

### ISSUE THREAD

**Issue by mprahl** [StackFocus/PostMaster#163]
Tag it and deploy the docs

**Comment by thatarchguy** [comment]
once #166 gets addressed I'll cut the release

**Comment by PrahlM93** [comment]
I think this is ready to go.

**Comment by PrahlM93** [comment]
@thatarchguy I updated the docs and tagged the release, but the package hasn't been updated:
https://bintray.com/stackfocus/deb/PostMaster
