### ISSUE TITLE
Convert to ldap3

### ISSUE THREAD

**Issue by thatarchguy** [StackFocus/PostMaster#167]
This will help get us on python 3

https://github.com/StackFocus/PostMaster/issues/95#issuecomment-242275179

**Comment by mprahl** [comment]
I'm working on this and my branch is at:
https://github.com/StackFocus/PostMaster/tree/ldap3-migration

I am having problems with the unit tests though as explained here:
https://github.com/cannatag/ldap3/issues/240

**Comment by mprahl** [comment]
#179 addresses this
