### ISSUE TITLE
Migrate Ansible Role To A Separate Repository

### ISSUE THREAD

**Issue by mprahl** [StackFocus/PostMaster#181]
**User Story:**
As a system's administrator, I'd like to be able to deploy my mail server using Ansible. I'd like to be able to use an officially supported Ansible role from Ansible Galaxy (or just GitHub) that installs PostMaster so that I can include that role in my `deploy-mailserver` playbook.

**Action Items:**
* Create a GitHub repository in the StackFocus organization called `ansible-postmaster`
* Migrate the `postmaster_deploy` role to the `ansible-postmaster` repo
* Offload MySQL installation and configuration to a role in Ansible Galaxy
* Consolidate the `postmaster_deploy` and `postmaster_upgrade` roles to be just one idempotent role
* Make the database migration be triggered by a role variable (in the event someone wants to redeploy PostMaster but is not ready for an upgrade/database migration)
* Have our deb package ingest this new Ansible role

**Comment by mprahl** [comment]
I made a pull request to add the Ansible role:
https://github.com/StackFocus/ansible-postmaster/pull/1

**Comment by thatarchguy** [comment]
Will we somehow include that role in Postmaster's package for installation and remove ansible from this repository?

**Comment by mprahl** [comment]
@thatarchguy Yeah I was planning that.

**Comment by mprahl** [comment]
#187 addresses this
